mysql:
  image: percona:5.7
  expose:
    - "3306"
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: app
    MYSQL_ROOT_PASSWORD: app

web:
  image: openresty/openresty:alpine
  links:
    - mysql:mysql
  ports:
    - "6606:3306"
  volumes:
    - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    - ./lua:/usr/local/openresty/nginx/lua
